AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
    Enabled: false

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - 'test/**/*.rb'
    - "spec/**/*"
    - "link_community.gemspec"
